### ISSUE TITLE
Cannot excute the bat file because of missing folder C:/Python27

### ISSUE THREAD

**Issue by ankhili** [Esri/mdcs-py#47] opened 2019-11-07 01:17 UTC
I uninstalled ArcMap and so the folder C:/Python27 was also uninstalled. 
I have Pro on my machine but the Python repo is not installed on C:/ as ArcMap. 
The tool doesn't work if this file is not available...

![image](https://user-images.githubusercontent.com/14264897/68351736-a3556100-0104-11ea-85ef-42f34b217852.png)

**Comment by vijaygit02** [comment] 2019-11-07 07:18
Hi Ankhili,
If you have Pro then you can find the Pro python exe here c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\python.exe 

Vijay

**Comment by abhiataero** [comment] 2020-01-29 05:44
@ankhili  i am closing the issue as it seems the problem is resolved

**Closed by abhiataero** 2020-01-29 05:44 UTC
